services:
  - type: web
    name: todolist-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://todolist-app.onrender.com # (tu pourras l’ajuster après déploiement)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: todolist-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: todolist-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: todolist-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: todolist-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todolist-db
          property: password

databases:
  - name: todolist-db
    plan: free
    databaseName: todolist
